spring:
  datasource:
    generate-unique-name: false
    name: taco_cloud
  jpa:
    hibernate:
      ddl-auto: create-drop
      defer-datasource-initialization: true
taco:
  orders:
    page-size: 10
logging:
  level:
    tacos: DEBUG

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
  logging:
    level:
      tacos: WARN