server:
  port: 9000
#end::portNineThousand[]

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    hibernate:
      ddl-auto: create-drop
      defer-datasource-initialization: true