server:
  port: 9090

# tag::client_config[]
# tag::provider_config_0[]
spring:
  security:
    oauth2:
      client:
        # end::provider_config_0[]
        registration:
          taco-admin-client-oidc:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://client:9090/login/oauth2/code/{registrationId}"
            scope: openid,writeIngredients,deleteIngredients
            client-name: taco-admin-client-oidc
        provider:
          tacocloud:
            issuer-uri: http://auth-server:9000